executor: slurm
jobs: 100
latency-wait: 500

default-resources:
#  name: "'{rule},{wildcards}'" # -J
  slurm_partition: general # -p
  runtime: 4320 # -t
  cpus_per_task: 1 # -c
  mem_mb_per_cpu: 64G # --mem-per-cpu
  nodes: 1
  output: "'output/logs_slurm/{rule}.{wildcards}.{jobid}.out'"
  error: "'output/logs_slurm/{rule}.{wildcards}.{jobid}.err'"
